services:
  watchtower:
    container_name: home-media-watchtower
    restart: unless-stopped
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  transmission:
    container_name: home-media-transmission
    restart: unless-stopped
    image: ghcr.io/linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
     - ./docker-volumes/home-media-transmission-config:/config
     - /nfs/media/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  radarr:
    container_name: home-media-radarr
    restart: unless-stopped
    image: ghcr.io/linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker-volumes/home-media-radarr-config:/config
      - /nfs/media/media/movies:/movies
      - /nfs/media/torrents:/downloads
    ports:
      - 7878:7878

  sonarr:
    container_name: home-media-sonarr
    restart: unless-stopped
    image: ghcr.io/linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker-volumes/home-media-sonarr-config:/config
      - /nfs/media/media/tv:/tv
      - /nfs/media/torrents:/downloads
    ports:
      - 8989:8989

  jellyfin:
      container_name: home-media-jellyfin
      restart: unless-stopped
      image: ghcr.io/linuxserver/jellyfin
      ports:
        - 8096:8096
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London     
      volumes:
        - ./docker-volumes/home-media-jellyfin-config:/config    
        - /nfs/media/media/movies:/movies      
        - /nfs/media/media/tv:/tv      
    
  notifiarr:
      container_name: home-media-notifiarr
      restart: unless-stopped
      image: golift/notifiarr
      ports:
        - 5454:5454
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - ./docker-volumes/home-media-notifiarr-config:/config

  nzbget:
    container_name: home-media-nzbget
    restart: unless-stopped
    image: lscr.io/linuxserver/nzbget:latest
    ports:
      - 6789:6789
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker-volumes/home-media/nzbget-config:/config
      - /nfs/media/torrents:/downloads

  prowlarr:
    restart: unless-stopped
    container_name: home-media-prowlarr
    image: linuxserver/prowlarr
    ports:
      - 9696:9696
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - ./docker-volumes.home-media-prowlarr-config:/config

  jellyseerr:
    container_name: home-media-jellyseerr
    restart: unless-stopped
    image: ghcr.io/fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker-volumes/home-media-jellyseerr-config:/config
    ports:
      - 5055:5055 
   
